/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BreadcrumbContent: typeof import('./src/components/BreadcrumbContent.vue')['default']
    FooterContent: typeof import('./src/components/FooterContent.vue')['default']
    ForceHiddenSidebarButton: typeof import('./src/components/ForceHiddenSidebarButton.vue')['default']
    HeaderContent: typeof import('./src/components/HeaderContent.vue')['default']
    Hitokoto: typeof import('./src/components/Hitokoto.vue')['default']
    ParseProblemList: typeof import('./src/components/problem/ParseProblemList.vue')['default']
    ParseUserList: typeof import('./src/components/user/ParseUserList.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SecretPanel: typeof import('./src/components/SecretPanel.vue')['default']
    SidebarContent: typeof import('./src/components/SidebarContent.vue')['default']
    TAside: typeof import('tdesign-vue-next')['Aside']
    TBackTop: typeof import('tdesign-vue-next')['BackTop']
    TButton: typeof import('tdesign-vue-next')['Button']
    TContent: typeof import('tdesign-vue-next')['Content']
    THeader: typeof import('tdesign-vue-next')['Header']
    TLayout: typeof import('tdesign-vue-next')['Layout']
  }
}
