/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BreadcrumbContent: typeof import('./src/components/BreadcrumbContent.vue')['default']
    FooterContent: typeof import('./src/components/FooterContent.vue')['default']
    ForceHiddenSidebarButton: typeof import('./src/components/ForceHiddenSidebarButton.vue')['default']
    HeaderContent: typeof import('./src/components/HeaderContent.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SidebarContent: typeof import('./src/components/SidebarContent.vue')['default']
    TAside: typeof import('tdesign-vue-next')['Aside']
    TBackTop: typeof import('tdesign-vue-next')['BackTop']
    TButton: typeof import('tdesign-vue-next')['Button']
    TCard: typeof import('tdesign-vue-next')['Card']
    TCol: typeof import('tdesign-vue-next')['Col']
    TContent: typeof import('tdesign-vue-next')['Content']
    THeader: typeof import('tdesign-vue-next')['Header']
    THeadMenu: typeof import('tdesign-vue-next')['HeadMenu']
    TIcon: typeof import('tdesign-vue-next')['Icon']
    TLayout: typeof import('tdesign-vue-next')['Layout']
    TLoading: typeof import('tdesign-vue-next')['Loading']
    TMenu: typeof import('tdesign-vue-next')['Menu']
    TMenuGroup: typeof import('tdesign-vue-next')['MenuGroup']
    TMenuItem: typeof import('tdesign-vue-next')['MenuItem']
    TRow: typeof import('tdesign-vue-next')['Row']
  }
}
